name: delivery_food
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.1+1
  enhance_stepper: ^0.1.1
  tuple: ^2.0.0
  flutter_switch: ^0.3.2
  xml: ^6.1.0
  table_calendar: ^3.0.6
  mobile_scanner: ^2.0.0
  http: ^0.13.5
  get_storage: ^2.0.3
  shared_preferences: ^2.0.15

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/button_bar/

